/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignInOtpRouteImport } from './routes/auth/sign-in-otp'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppWorkspaceIdRouteRouteImport } from './routes/app/$workspaceId/route'
import { Route as AppWorkspaceIdIndexRouteImport } from './routes/app/$workspaceId/index'
import { Route as AppWorkspaceIdSettingsRouteImport } from './routes/app/$workspaceId/settings'
import { Route as AppWorkspaceIdMembersRouteImport } from './routes/app/$workspaceId/members'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignInOtpRoute = AuthSignInOtpRouteImport.update({
  id: '/auth/sign-in-otp',
  path: '/auth/sign-in-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIdRouteRoute = AppWorkspaceIdRouteRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceIdIndexRoute = AppWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdSettingsRoute = AppWorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)
const AppWorkspaceIdMembersRoute = AppWorkspaceIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppWorkspaceIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$workspaceId': typeof AppWorkspaceIdRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-in-otp': typeof AuthSignInOtpRoute
  '/app/': typeof AppIndexRoute
  '/app/$workspaceId/members': typeof AppWorkspaceIdMembersRoute
  '/app/$workspaceId/settings': typeof AppWorkspaceIdSettingsRoute
  '/app/$workspaceId/': typeof AppWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/account': typeof AppAccountRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-in-otp': typeof AuthSignInOtpRoute
  '/app': typeof AppIndexRoute
  '/app/$workspaceId/members': typeof AppWorkspaceIdMembersRoute
  '/app/$workspaceId/settings': typeof AppWorkspaceIdSettingsRoute
  '/app/$workspaceId': typeof AppWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$workspaceId': typeof AppWorkspaceIdRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-in-otp': typeof AuthSignInOtpRoute
  '/app/': typeof AppIndexRoute
  '/app/$workspaceId/members': typeof AppWorkspaceIdMembersRoute
  '/app/$workspaceId/settings': typeof AppWorkspaceIdSettingsRoute
  '/app/$workspaceId/': typeof AppWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$workspaceId'
    | '/app/account'
    | '/auth/sign-in'
    | '/auth/sign-in-otp'
    | '/app/'
    | '/app/$workspaceId/members'
    | '/app/$workspaceId/settings'
    | '/app/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/account'
    | '/auth/sign-in'
    | '/auth/sign-in-otp'
    | '/app'
    | '/app/$workspaceId/members'
    | '/app/$workspaceId/settings'
    | '/app/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$workspaceId'
    | '/app/account'
    | '/auth/sign-in'
    | '/auth/sign-in-otp'
    | '/app/'
    | '/app/$workspaceId/members'
    | '/app/$workspaceId/settings'
    | '/app/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignInOtpRoute: typeof AuthSignInOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-in-otp': {
      id: '/auth/sign-in-otp'
      path: '/auth/sign-in-otp'
      fullPath: '/auth/sign-in-otp'
      preLoaderRoute: typeof AuthSignInOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceId': {
      id: '/app/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/app/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceId/': {
      id: '/app/$workspaceId/'
      path: '/'
      fullPath: '/app/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/app/$workspaceId/settings': {
      id: '/app/$workspaceId/settings'
      path: '/settings'
      fullPath: '/app/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspaceIdSettingsRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
    '/app/$workspaceId/members': {
      id: '/app/$workspaceId/members'
      path: '/members'
      fullPath: '/app/$workspaceId/members'
      preLoaderRoute: typeof AppWorkspaceIdMembersRouteImport
      parentRoute: typeof AppWorkspaceIdRouteRoute
    }
  }
}

interface AppWorkspaceIdRouteRouteChildren {
  AppWorkspaceIdMembersRoute: typeof AppWorkspaceIdMembersRoute
  AppWorkspaceIdSettingsRoute: typeof AppWorkspaceIdSettingsRoute
  AppWorkspaceIdIndexRoute: typeof AppWorkspaceIdIndexRoute
}

const AppWorkspaceIdRouteRouteChildren: AppWorkspaceIdRouteRouteChildren = {
  AppWorkspaceIdMembersRoute: AppWorkspaceIdMembersRoute,
  AppWorkspaceIdSettingsRoute: AppWorkspaceIdSettingsRoute,
  AppWorkspaceIdIndexRoute: AppWorkspaceIdIndexRoute,
}

const AppWorkspaceIdRouteRouteWithChildren =
  AppWorkspaceIdRouteRoute._addFileChildren(AppWorkspaceIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceIdRouteRoute: typeof AppWorkspaceIdRouteRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceIdRouteRoute: AppWorkspaceIdRouteRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignInOtpRoute: AuthSignInOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
