import { db } from '../database-client';
import { WorkspaceService } from './workspace/workspace.service';
import { TicketsService } from './ticket/tickets.service';
import { TicketAttachmentsService } from './ticket/ticketAttachments.service';
import { TicketLabelsService } from './ticket/ticketLabels.service';
import { TicketCommentsService } from './ticket/ticketComments.service';
import { WorkspaceMemberService } from './workspace/workspaceMember.service';
import { TicketAssigneeService } from './ticket/ticketAssignee.service';
import { TicketReporterService } from './ticket/ticketReporter.service';
import { TicketListsService } from './ticket/ticketList.service';
import { StorageService } from './storage/storage.service';
import { WorkspaceTicketLabelService } from './workspace/workspaceTicketLabel.service';
import { WorkspaceMemberInviteService } from './workspace/workspaceMemberInvite.service';
import { UserService } from './user/user.service';

export const userService: UserService = new UserService(db);
export const workspaceService: WorkspaceService = new WorkspaceService(db);
export const workspaceMemberService: WorkspaceMemberService = new WorkspaceMemberService(db);
export const workspaceTicketLabelService: WorkspaceTicketLabelService = new WorkspaceTicketLabelService(db);
export const workspaceMemberInviteService: WorkspaceMemberInviteService = new WorkspaceMemberInviteService(db);
export const ticketsService: TicketsService = new TicketsService(db);
export const ticketListsService: TicketListsService = new TicketListsService(db);
export const ticketAssigneeService: TicketAssigneeService = new TicketAssigneeService(db);
export const ticketReporterService: TicketReporterService = new TicketReporterService(db);
export const ticketAttachmentsService = new TicketAttachmentsService(db);
export const ticketCommentsService: TicketCommentsService = new TicketCommentsService(db);
export const ticketLabelsService: TicketLabelsService = new TicketLabelsService(db);
export const storageService: StorageService = new StorageService(db);
